<?php

namespace Database\Seeders;

use App\Models\Plan;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        //TODO
        //پلن ها باید حرفه ای چیده شود
        //Plan Seeder
        Plan::insert([
            [
                'name' => 'نسخه آزمایشی(trial)',
                'code' => 'trial',
                'slug' => 'trial',
                'description' => 'نسخه نامحدود 14 روزه',
                'monthly_price' => 0,
                'yearly_price' => 0,
                'currency' => 'IRT',
                'duration_days' => 14,  // مدت‌دار نیست (تا وقتی کنسل نکنی)
                'limits' => json_encode([
                    'max_products' => null,
                    'max_users' => 5,
                    'max_warehouses' => 5,
                    'max_invoices_month' => null,
                    'max_organizations' => 3,
                    'storage_mb' => 200,
                    'support' => 'ticket',
                    'custom_domain' => false,
                    'export_excel' => true,
                    'export_pdf' => true,
                    'max_categories' => null,
                    'max_brands' => null,
                    'max_suppliers' => 500,
                    'max_product_images' => 5,
                    'max_stock_locations' => 50,
                    'max_import_rows' => 1000,
                    'activity_log_days' => 30,
                    'max_organizational_units_per_org' => 5,
                ]),
                'features' => json_encode([
                    'core_inventory',
                    'invoices',
                    'havale',
                    'advanced_reports',
                    'repairs',
                    'scrap',
                    'notifications',
                    'api',
                ]),
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'پایه (رایگان)',
                'code' => 'basic',
                'slug' => 'basic',
                'description' => 'مناسب استارت‌آپ‌ها و کسب‌وکارهای کوچک',
                'monthly_price' => 0,
                'yearly_price' => 0,
                'currency' => 'IRT',
                'duration_days' => null,  // مدت‌دار نیست (تا وقتی کنسل نکنی)
                'limits' => json_encode([
                    'max_products' => 100,
                    'max_users' => 1,
                    'max_warehouses' => 1,
                    'max_invoices_month' => 30,
                    'max_organizations' => 1,
                    'storage_mb' => 50,
                    'support' => 'ticket',
                    'custom_domain' => false,
                    'export_excel' => true,
                    'export_pdf' => false,
                    'max_categories' => 20,
                    'max_brands' => 10,
                    'max_suppliers' => 50,
                    'max_product_images' => 2,
                    'max_stock_locations' => 10,
                    'max_import_rows' => 100,
                    'activity_log_days' => 7,
                    'max_organizational_units_per_org' => 1,
                ]),
                'features' => json_encode([
                    'core_inventory',
                    'invoices',
                    'havale',
                    'basic_reports',
                ]),
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'حرفه‌ای',
                'code' => 'pro',
                'slug' => 'pro',
                'description' => 'مناسب شرکت‌های در حال رشد',
                'monthly_price' => 390000,
                'yearly_price' => 3900000,
                'currency' => 'IRT',
                'duration_days' => 30,
                'limits' => json_encode([
                    'max_products' => 1000,
                    'max_users' => 5,
                    'max_warehouses' => 3,
                    'max_invoices_month' => 200,
                    'max_organizations' => 3,
                    'storage_mb' => 200,
                    'support' => 'priority',
                    'custom_domain' => false,
                    'export_excel' => true,
                    'export_pdf' => true,
                    'max_categories' => 50,
                    'max_brands' => 30,
                    'max_suppliers' => 200,
                    'max_product_images' => 4,
                    'max_stock_locations' => 30,
                    'max_import_rows' => 500,
                    'activity_log_days' => 30,
                    'max_organizational_units_per_org' => 3,
                ]),
                'features' => json_encode([
                    'core_inventory',
                    'invoices',
                    'havale',
                    'advanced_reports',
                    'repairs',
                    'scrap',
                    'notifications',
                ]),
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'تجاری',
                'code' => 'business',
                'slug' => 'business',
                'description' => 'مناسب کسب‌وکارهای متوسط با چند شعبه',
                'monthly_price' => 990000,
                'yearly_price' => 9900000,
                'currency' => 'IRT',
                'duration_days' => 30,
                'limits' => json_encode([
                    'max_products' => 5000,
                    'max_users' => 15,
                    'max_warehouses' => 10,
                    'max_invoices_month' => 1000,
                    'max_organizations' => 10,
                    'storage_mb' => 500,
                    'support' => 'priority',
                    'custom_domain' => true,
                    'export_excel' => true,
                    'export_pdf' => true,
                    'max_categories' => 200,
                    'max_brands' => 100,
                    'max_suppliers' => 1000,
                    'max_product_images' => 6,
                    'max_stock_locations' => 100,
                    'max_import_rows' => 2000,
                    'activity_log_days' => 90,
                    'max_organizational_units_per_org' => 10,
                ]),
                'features' => json_encode([
                    'core_inventory',
                    'invoices',
                    'havale',
                    'advanced_reports',
                    'repairs',
                    'scrap',
                    'notifications',
                    'api',
                ]),
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'سازمانی',
                'code' => 'enterprise',
                'slug' => 'enterprise',
                'description' => 'برای هلدینگ‌ها و سازمان‌های بزرگ؛ بدون محدودیت',
                'monthly_price' => 1890000,
                'yearly_price' => 18900000,
                'currency' => 'IRT',
                'duration_days' => 30,
                'limits' => json_encode([
                    'max_products' => null,
                    'max_users' => null,
                    'max_warehouses' => null,
                    'max_invoices_month' => null,
                    'max_organizations' => null,
                    'storage_mb' => 2048,
                    'support' => 'dedicated',
                    'custom_domain' => true,
                    'export_excel' => true,
                    'export_pdf' => true,
                    'max_categories' => null,
                    'max_brands' => null,
                    'max_suppliers' => null,
                    'max_product_images' => 10,
                    'max_stock_locations' => null,
                    'max_import_rows' => null,
                    'activity_log_days' => 365,
                    'max_organizational_units_per_org' => null,
                ]),
                'features' => json_encode([
                    'core_inventory',
                    'invoices',
                    'havale',
                    'advanced_reports',
                    'repairs',
                    'scrap',
                    'notifications',
                    'api',
                    'white_label',
                ]),
                'is_active' => true,
                'sort_order' => 5,
            ],
        ]);
    }
}
